[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2024"

[dependencies]
delegate = "0.13.2"
env_logger = "0.11.6"
euclid = "0.22.11"
hsl = "0.1.1"
indicatif = "0.17.9"
log = "0.4.25"
minifb = "0.27.0"
num = "0.4.3"
palette = "0.7.6"
parking_lot = "0.12.3"
rayon = "1.10.0"
#waker_interrupter = { git = "https://github.com/gorilskij/waker_interrupter" }
waker_interrupter = { path = "../waker_interrupter" }
simd_quad = { path = "../simd_quad" }
gat-lending-iterator = "0.1.6"

[profile.dev]
lto = "fat"

[profile.release]
lto = "fat"
